"""Added onto the user model

Revision ID: 01b95ca85c92
Revises: db3e0a803b3b
Create Date: 2023-12-06 10:30:27.721154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b95ca85c92'
down_revision = 'db3e0a803b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('family_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('family_name')
        batch_op.drop_column('given_name')

    # ### end Alembic commands ###
